# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudyCat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyCat
  pod 'Firebase', '>= 2.5.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  target 'StudyCatTests' do
    inherit! :search_paths
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    # Pods for testing
  end

  target 'StudyCatUITests' do
    inherit! :search_paths
    pod 'Firebase'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    # Pods for testing
  end

end
